[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
DEBUG = "false"
PORT = "8000" 